//! ArcVector — vector similarity search as an arcus ASCII protocol extension.
//!
//! ```text
//! lib.rs        registration and the four memcached callbacks  <- FFI boundary
//!   wire/       socket bytes -> typed request
//!     protocol    reading a token array, writing one response
//!     request     command line -> typed request                (pure)
//!     pending     state for the two commands that carry a body
//!   command     one handler per command
//!   registry    live indexes and the lazy rebuild
//!   store       arcus Map engine access                        (all raw pointers)
//!   index       usearch wrapper and concurrency
//!   vector/     how a vector and its attributes are represented (pure)
//!     codec       element byte layout
//!     quant       f32 -> f16/i8/b1
//!     filter      attribute filter expressions
//!   error       one error type, and who gets blamed for it
//! ```
//!
//! The single consistency rule: **the usearch index is a cache rebuildable from
//! Map. If it is not in Map, it does not exist.** Restart, eviction, TTL expiry
//! and replication slaves all follow from that.
//!
//! See `docs/INTERNALS.md` for how the pieces fit together and `README.md` for
//! the command reference.

/// Bindings to arcus's `engine_interface_v1`, generated by bindgen in `build.rs`.
///
/// Included from `OUT_DIR` so the build never writes into the source tree. None of
/// the lints this generated code trips are ours to fix.
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    unnecessary_transmutes,
    clippy::all,
    clippy::pedantic
)]
pub mod engine_api {
    include!(concat!(env!("OUT_DIR"), "/engine_api.rs"));
}

pub mod command;
pub mod error;
pub mod index;
pub mod registry;
pub mod store;
pub mod vector;
pub mod wire;

use std::os::raw::{c_char, c_int, c_void};
use std::ptr;

use engine_api::{
    EXTENSION_ASCII_PROTOCOL_DESCRIPTOR, EXTENSION_ERROR_CODE,
    EXTENSION_ERROR_CODE_EXTENSION_FATAL, EXTENSION_ERROR_CODE_EXTENSION_SUCCESS, GET_SERVER_API,
    extension_type_t_EXTENSION_ASCII_PROTOCOL, token_t,
};
use error::{Error, Reply, Result};
use store::{Store, StoreError};
use wire::pending;
use wire::protocol::{Responder, ResponseHandler, Tokens};
use wire::request::{self, Body, Line, MAX_BODY_BYTES};

/// Engine access for the callback currently running.
///
/// # Safety
///
/// `cookie` must be the cookie memcached passed to that callback.
unsafe fn store_for(cookie: *const c_void) -> Result<Store> {
    // SAFETY: guaranteed by the caller.
    unsafe { Store::for_cookie(cookie) }.ok_or(Error::Store(StoreError::Unavailable))
}

/// Run a request whose command line said everything.
fn run_line(store: &Store, line: Line) -> Result<Reply> {
    match line {
        Line::Create(spec) => command::vcreate(store, &spec),
        Line::SimKey(spec) => command::vsim_key(store, &spec),
        Line::Get { index, id } => command::vget(store, index, id),
        Line::Del { index, id } => command::vdel(store, index, id),
        Line::Drop { index } => command::vdrop(store, index),
        Line::List => command::vlist(),
    }
}

/// Run a request once its body has arrived.
fn run_body(store: &Store, body: Body, bytes: &[u8]) -> Result<Reply> {
    match body {
        Body::Add(spec) => command::vadd(store, &spec, bytes),
        Body::Sim(spec) => command::vsim_vector(store, &spec, bytes),
    }
}

/// Route one command line, or resume one whose body has arrived.
///
/// # Safety
///
/// `tokens` must borrow the argument vector memcached passed to `execute`, and
/// `cookie` must be that call's connection cookie.
unsafe fn dispatch(cookie: *const c_void, tokens: &Tokens) -> Result<Reply> {
    // SAFETY: guaranteed by the caller.
    let store = unsafe { store_for(cookie) };

    // An empty argument vector means a body arrived for a two-phase command.
    if tokens.is_empty() {
        let pending =
            pending::take_body(cookie).ok_or_else(|| Error::bad_request("lost command state"))?;
        let (request, bytes) = pending.into_parts();
        return run_body(&store?, request?, &bytes);
    }

    // A body-carrying line reaching `execute` means `accept` could not size its
    // body; otherwise the body phase above would have handled it.
    if let Some(at) = request::body_length_at(tokens) {
        let what = if at == 3 {
            "vector length"
        } else {
            "vector bytes"
        };
        return Err(request::body_length_error(tokens, at, what));
    }

    run_line(&store?, request::parse_line(tokens)?)
}

/// Decide how much body a command needs before it can run.
///
/// Only the byte count is examined. Everything else on the line is parsed too, but
/// a failure is *carried into* the pending state rather than refusing the command:
/// refusing would leave the body unread, and memcached would then parse those
/// bytes as the next command line.
///
/// Returning `true` without setting `ndata` is therefore reserved for a byte count
/// that cannot be read at all, since without one there is no way to know how much
/// to drain.
///
/// # Safety
///
/// `argv`, `ndata` and `ptr_out` must be the parameters memcached passed to the
/// `accept` callback.
unsafe extern "C" fn accept_vector_cmd(
    _cmd_cookie: *const c_void,
    cookie: *mut c_void,
    argc: c_int,
    argv: *mut token_t,
    ndata: *mut usize,
    ptr_out: *mut *mut c_char,
) -> bool {
    // SAFETY: guaranteed by the caller.
    let tokens = unsafe { Tokens::new(argv, argc) };

    let Some(at) = request::body_length_at(&tokens) else {
        // Either handled from the command line, or not ours at all.
        return tokens.command().is_some();
    };
    let Ok(body_len) = tokens.parse::<usize>(at, "length") else {
        return true;
    };
    if body_len > MAX_BODY_BYTES {
        return true;
    }

    // SAFETY: guaranteed by the caller.
    unsafe {
        pending::expect_body(
            cookie,
            request::parse_body(&tokens),
            body_len,
            ndata,
            ptr_out,
        );
    }
    true
}

/// # Safety
///
/// `argv` and `handler` must be the parameters memcached passed to `execute`.
unsafe extern "C" fn execute_vector_cmd(
    _cmd_cookie: *const c_void,
    cookie: *const c_void,
    argc: c_int,
    argv: *mut token_t,
    handler: ResponseHandler,
) -> bool {
    // SAFETY: guaranteed by the caller.
    let tokens = unsafe { Tokens::new(argv, argc) };
    // SAFETY: `cookie` belongs to the call in progress.
    let outcome = unsafe { dispatch(cookie, &tokens) };
    Responder::new(handler, cookie).reply(outcome);
    true
}

/// Release a body whose command never completed.
unsafe extern "C" fn abort_vector_cmd(_cmd_cookie: *const c_void, cookie: *const c_void) {
    drop(pending::take_body(cookie));
}

unsafe extern "C" fn get_name_vector(_cmd_cookie: *const c_void) -> *const c_char {
    c"arcus-vector-db".as_ptr()
}

static mut VECTOR_DESCRIPTOR: EXTENSION_ASCII_PROTOCOL_DESCRIPTOR =
    EXTENSION_ASCII_PROTOCOL_DESCRIPTOR {
        get_name: Some(get_name_vector),
        get_auth_flag: None,
        accept: Some(accept_vector_cmd),
        execute: Some(execute_vector_cmd),
        abort: Some(abort_vector_cmd),
        cookie: ptr::null_mut(),
        next: ptr::null_mut(),
    };

/// Entry point memcached calls when loading the extension.
#[unsafe(no_mangle)]
pub extern "C" fn memcached_extensions_initialize(
    _config: *const c_char,
    get_server_api: GET_SERVER_API,
) -> EXTENSION_ERROR_CODE {
    let Some(get_api) = get_server_api else {
        return EXTENSION_ERROR_CODE_EXTENSION_FATAL;
    };
    store::set_server_api(get_api);

    // SAFETY: memcached hands us a live SERVER_HANDLE_V1 accessor, and the
    // descriptor is a process-lifetime static that the server only reads.
    unsafe {
        let server = get_api();
        if server.is_null() {
            return EXTENSION_ERROR_CODE_EXTENSION_FATAL;
        }
        let extension = (*server).extension;
        if extension.is_null() {
            return EXTENSION_ERROR_CODE_EXTENSION_FATAL;
        }
        let Some(register) = (*extension).register_extension else {
            return EXTENSION_ERROR_CODE_EXTENSION_FATAL;
        };
        if !register(
            extension_type_t_EXTENSION_ASCII_PROTOCOL,
            (&raw mut VECTOR_DESCRIPTOR).cast::<c_void>(),
        ) {
            return EXTENSION_ERROR_CODE_EXTENSION_FATAL;
        }
    }
    EXTENSION_ERROR_CODE_EXTENSION_SUCCESS
}
