//! ArcVector — vector search as an arcus ASCII protocol extension.
//!
//! ```text
//! lib.rs      extension registration and the memcached callbacks
//!   protocol  argument access, replies, the nread body transfer
//!   command   one handler per command
//!   registry  live indexes and the lazy rebuild
//!   store     arcus Map engine access          (all raw pointers live here)
//!   index     usearch wrapper and concurrency
//!   codec     element byte layout              (pure)
//!   quant     f32 -> f16/i8/b1                 (pure)
//!   filter    filter expressions               (pure)
//! ```
//!
//! The single consistency rule: **the usearch index is a cache rebuildable from
//! Map. If it is not in Map, it does not exist.** Restart, eviction, TTL expiry
//! and replication slaves are all covered by it.

// Generated by bindgen from the arcus C headers; none of its lints are ours to fix.
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    unnecessary_transmutes,
    clippy::all,
    clippy::pedantic
)]
pub mod engine_api;

pub mod codec;
pub mod command;
pub mod error;
pub mod filter;
pub mod index;
pub mod protocol;
pub mod quant;
pub mod registry;
pub mod store;

use std::os::raw::{c_char, c_int, c_void};
use std::ptr;

use engine_api::{
    EXTENSION_ASCII_PROTOCOL_DESCRIPTOR, EXTENSION_ERROR_CODE,
    EXTENSION_ERROR_CODE_EXTENSION_FATAL, EXTENSION_ERROR_CODE_EXTENSION_SUCCESS, GET_SERVER_API,
    extension_type_t_EXTENSION_ASCII_PROTOCOL, token_t,
};
use error::{Error, Reply, Result};
use protocol::{Cmd, MAX_BLOB_BYTES, PendingCmd, Responder, ResponseHandler, SimSource, Tokens};
use store::{Store, StoreError};

/// Engine access for the callback currently running.
///
/// # Safety
///
/// `cookie` must be the cookie memcached passed to that callback.
unsafe fn store_for(cookie: *const c_void) -> Result<Store> {
    // SAFETY: guaranteed by the caller.
    unsafe { Store::for_cookie(cookie) }.ok_or(Error::Store(StoreError::Unavailable))
}

/// Route one command line, or resume one whose body has arrived.
///
/// # Safety
///
/// `tokens` must borrow the argument vector memcached passed to `execute`, and
/// `cookie` must be that call's connection cookie.
unsafe fn dispatch(cookie: *const c_void, tokens: &Tokens) -> Result<Reply> {
    // SAFETY: guaranteed by the caller.
    let store = unsafe { store_for(cookie) };

    // An empty argument vector means the body of a two-phase command arrived.
    if tokens.is_empty() {
        let pending =
            protocol::take_body(cookie).ok_or_else(|| Error::bad_request("lost command state"))?;
        let store = store?;
        let (cmd, body) = pending.into_parts();
        return match cmd {
            PendingCmd::Add { index, id, attr } => {
                command::vadd(&store, &index, &id, &attr?, &body)
            }
            PendingCmd::Sim {
                index,
                k,
                dim,
                filter,
            } => command::vsim_vector(&store, &index, k, dim, filter?.as_ref(), &body),
        };
    }

    match tokens.command() {
        Some(Cmd::VCreate) => command::vcreate(&store?, tokens),
        Some(Cmd::VGet) => command::vget(&store?, tokens),
        Some(Cmd::VDel) => command::vdel(&store?, tokens),
        Some(Cmd::VDrop) => command::vdrop(&store?, tokens),
        Some(Cmd::VList) => command::vlist(tokens),
        // VSIM KEY needs no body and lands here; VSIM VECTOR completes through
        // the body phase above.
        Some(Cmd::VSim) => vsim(&store?, tokens),
        // A well-formed vadd completes through the body phase above, so arriving
        // here means the line was refused there — say why.
        Some(Cmd::VAdd) => Err(body_command_error(tokens)),
        None => Err(Error::bad_request(format!(
            "unknown command {}",
            tokens.text(0).unwrap_or("")
        ))),
    }
}

/// `VSIM KEY <index> <num> <key> [FILTER <n> <term>...]`
///
/// The vector form is not answered here: it needs a body, so `accept` registers
/// it and `dispatch` resumes it once the coordinates arrive.
fn vsim(store: &Store, tokens: &Tokens) -> Result<Reply> {
    if tokens.len() < 5 {
        return Err(Error::bad_request("bad command line format"));
    }
    let source = SimSource::parse(tokens.text(1)?).ok_or_else(|| {
        Error::bad_request(format!(
            "expected VECTOR or KEY, got '{}'",
            tokens.text(1).unwrap_or("")
        ))
    })?;
    if source != SimSource::Key {
        // VECTOR needs a body, so reaching here means accept refused the line.
        return Err(body_command_error(tokens));
    }

    let index = tokens.text(2)?;
    let k: usize = tokens.parse(3, "result count")?;
    if k == 0 {
        return Err(Error::bad_request("result count must be at least 1"));
    }
    let key = tokens.text(4)?;
    let filter = tokens.filter_clause(5)?;
    command::vsim_key(store, index, k, key, filter.as_ref())
}

/// Byte count of an f32 vector payload.
///
/// A length that is not a positive multiple of four cannot describe `f32`
/// coordinates, so it is rejected here with the reason spelled out rather than
/// reported later as a generic format error.
fn vector_bytes(tokens: &Tokens, at: usize, what: &str) -> Result<usize> {
    let n: usize = tokens.parse(at, what)?;
    if n == 0 || !n.is_multiple_of(4) {
        return Err(Error::bad_request(format!(
            "{what} must be a positive multiple of 4 (dimensions x 4 bytes per f32), got {n}"
        )));
    }
    if n > MAX_BLOB_BYTES {
        return Err(Error::bad_request(format!(
            "{what} {n} exceeds the {MAX_BLOB_BYTES}-byte transfer limit"
        )));
    }
    Ok(n)
}

/// Read `ATTR <attrlen> <attr JSON>` off a `vadd` line.
///
/// The clause is optional; without it a vector is stored with no attributes.
/// `accept` cannot answer the client, so a malformed clause is carried as an
/// error for [`command::vadd`] to report.
fn read_attr(tokens: &Tokens) -> std::result::Result<Vec<u8>, Error> {
    if tokens.len() == 4 {
        return Ok(Vec::new());
    }
    let keyword = tokens.text(4)?;
    if !keyword.eq_ignore_ascii_case("ATTR") {
        return Err(Error::bad_request(format!(
            "expected ATTR after the vector length, got '{keyword}'"
        )));
    }
    let declared: usize = tokens.parse(5, "ATTR length")?;
    if declared > codec::ATTR_BYTES {
        return Err(Error::bad_request(format!(
            "ATTR is {declared} bytes, over the {}-byte limit",
            codec::ATTR_BYTES
        )));
    }
    if declared == 0 {
        return Ok(Vec::new());
    }

    // The declared length drives the read; `tail` verifies it against the span
    // the tokens cover, so a wrong length is reported rather than trusted.
    tokens.tail(6, declared)
}

/// Parse a command line that carries a body, returning what to register and how
/// many bytes to expect.
///
/// `accept` uses this to size the body and `execute` re-runs it to report why a
/// line was refused — `accept` has no channel to answer the client, so the two
/// share one implementation instead of one validating and the other guessing.
fn parse_body_command(tokens: &Tokens) -> Result<(PendingCmd, usize)> {
    let malformed = || Error::bad_request("bad command line format");
    match tokens.command() {
        // vadd <index> <id> <veclen> [ATTR <attrlen> <attr JSON>]
        Some(Cmd::VAdd) => {
            if tokens.len() < 4 {
                return Err(malformed());
            }
            let index = tokens.text(1)?.to_owned();
            let id = tokens.text(2)?.to_owned();
            let vec_bytes = vector_bytes(tokens, 3, "vector length")?;
            // The body is exactly the vector; ATTR was already on the line.
            let attr = read_attr(tokens);
            Ok((PendingCmd::Add { index, id, attr }, vec_bytes))
        }

        // VSIM VECTOR <index> <num> <bytes> <dim> [FILTER <n> <term>...]
        Some(Cmd::VSim) => {
            if tokens.len() < 6 {
                return Err(malformed());
            }
            let index = tokens.text(2)?.to_owned();
            let k: usize = tokens.parse(3, "result count")?;
            if k == 0 {
                return Err(Error::bad_request("result count must be at least 1"));
            }
            let bytes = vector_bytes(tokens, 4, "vector bytes")?;
            let dim: usize = tokens.parse(5, "dimension")?;
            if dim == 0 {
                return Err(Error::bad_request("dimension must be at least 1"));
            }
            let filter = tokens.filter_clause(6);
            Ok((
                PendingCmd::Sim {
                    index,
                    k,
                    dim,
                    filter,
                },
                bytes,
            ))
        }

        _ => Err(malformed()),
    }
}

/// Why a body-carrying line never reached its body phase.
fn body_command_error(tokens: &Tokens) -> Error {
    match parse_body_command(tokens) {
        Err(e) => e,
        // The line parses, so the body should have been registered and resumed.
        Ok(_) => Error::bad_request("lost command state"),
    }
}

/// Decide how much body a command needs before it can run.
///
/// Returning `true` without setting `ndata` makes memcached call `execute` on the
/// command line, where the refusal is reported.
///
/// # Safety
///
/// `argv`, `ndata` and `ptr_out` must be the parameters memcached passed to the
/// `accept` callback.
unsafe extern "C" fn accept_vector_cmd(
    _cmd_cookie: *const c_void,
    cookie: *mut c_void,
    argc: c_int,
    argv: *mut token_t,
    ndata: *mut usize,
    ptr_out: *mut *mut c_char,
) -> bool {
    // SAFETY: guaranteed by the caller.
    let tokens = unsafe { Tokens::new(argv, argc) };

    // Only vadd and VSIM VECTOR carry a body. Everything else — including
    // VSIM KEY, whose query is already in the index — is answered straight from
    // the command line.
    let vector_form = tokens.text(1).ok().and_then(SimSource::parse) == Some(SimSource::Vector);
    match tokens.command() {
        Some(Cmd::VAdd) => {}
        Some(Cmd::VSim) if vector_form => {}
        Some(_) => return true,
        None => return false,
    }

    // A refusal here cannot be reported, so it is left to execute(), which runs
    // the same parse and produces the same message.
    let Ok((pending, body_len)) = parse_body_command(&tokens) else {
        return true;
    };

    // SAFETY: guaranteed by the caller.
    unsafe { protocol::expect_body(cookie, pending, body_len, ndata, ptr_out) };
    true
}

/// # Safety
///
/// `argv` and `handler` must be the parameters memcached passed to `execute`.
unsafe extern "C" fn execute_vector_cmd(
    _cmd_cookie: *const c_void,
    cookie: *const c_void,
    argc: c_int,
    argv: *mut token_t,
    handler: ResponseHandler,
) -> bool {
    // SAFETY: guaranteed by the caller.
    let tokens = unsafe { Tokens::new(argv, argc) };
    // SAFETY: `cookie` belongs to the call in progress.
    let outcome = unsafe { dispatch(cookie, &tokens) };
    Responder::new(handler, cookie).reply(outcome);
    true
}

/// Release a body whose command never completed.
unsafe extern "C" fn abort_vector_cmd(_cmd_cookie: *const c_void, cookie: *const c_void) {
    drop(protocol::take_body(cookie));
}

unsafe extern "C" fn get_name_vector(_cmd_cookie: *const c_void) -> *const c_char {
    c"arcus-vector-db".as_ptr()
}

static mut VECTOR_DESCRIPTOR: EXTENSION_ASCII_PROTOCOL_DESCRIPTOR =
    EXTENSION_ASCII_PROTOCOL_DESCRIPTOR {
        get_name: Some(get_name_vector),
        get_auth_flag: None,
        accept: Some(accept_vector_cmd),
        execute: Some(execute_vector_cmd),
        abort: Some(abort_vector_cmd),
        cookie: ptr::null_mut(),
        next: ptr::null_mut(),
    };

/// Entry point memcached calls when loading the extension.
#[unsafe(no_mangle)]
pub extern "C" fn memcached_extensions_initialize(
    _config: *const c_char,
    get_server_api: GET_SERVER_API,
) -> EXTENSION_ERROR_CODE {
    let Some(get_api) = get_server_api else {
        return EXTENSION_ERROR_CODE_EXTENSION_FATAL;
    };
    store::set_server_api(get_api);

    // SAFETY: memcached hands us a live SERVER_HANDLE_V1 accessor, and the
    // descriptor is a process-lifetime static that the server only reads.
    unsafe {
        let server = get_api();
        if server.is_null() {
            return EXTENSION_ERROR_CODE_EXTENSION_FATAL;
        }
        let extension = (*server).extension;
        if extension.is_null() {
            return EXTENSION_ERROR_CODE_EXTENSION_FATAL;
        }
        let Some(register) = (*extension).register_extension else {
            return EXTENSION_ERROR_CODE_EXTENSION_FATAL;
        };
        if !register(
            extension_type_t_EXTENSION_ASCII_PROTOCOL,
            (&raw mut VECTOR_DESCRIPTOR).cast::<c_void>(),
        ) {
            return EXTENSION_ERROR_CODE_EXTENSION_FATAL;
        }
    }
    EXTENSION_ERROR_CODE_EXTENSION_SUCCESS
}

#[cfg(test)]
mod tests {
    use super::*;

    use protocol::tokenize_for_test as tokenize;

    fn attr_of(line: &str) -> Result<Vec<u8>> {
        let (_buf, raw) = tokenize(line);
        // SAFETY: `raw` and its buffer outlive the borrow.
        let tokens = unsafe { Tokens::new(raw.as_ptr(), raw.len() as c_int) };
        read_attr(&tokens)
    }

    fn refusal(line: &str) -> String {
        let (_buf, raw) = tokenize(line);
        // SAFETY: `raw` and its buffer outlive the borrow.
        let tokens = unsafe { Tokens::new(raw.as_ptr(), raw.len() as c_int) };
        body_command_error(&tokens).to_string()
    }

    #[test]
    fn a_vector_length_that_is_not_a_multiple_of_four_says_so() {
        // Regression: this used to surface as a bare "bad command line format",
        // which gave no hint that veclen counts bytes, not dimensions.
        let msg = refusal(r#"vadd index doc1 7 ATTR 23 {"abc":123,"def":"abc"}"#);
        assert!(msg.contains("multiple of 4"), "{msg}");
        assert!(msg.contains("got 7"), "{msg}");

        // 7 dimensions of f32 is 28 bytes, which is accepted, and the body is
        // sized to the vector alone since ATTR came off the line.
        let (_buf, raw) = tokenize(r#"vadd index doc1 28 ATTR 23 {"abc":123,"def":"abc"}"#);
        // SAFETY: `raw` and its buffer outlive the borrow.
        let tokens = unsafe { Tokens::new(raw.as_ptr(), raw.len() as c_int) };
        let (cmd, body_len) = parse_body_command(&tokens).unwrap();
        assert_eq!(body_len, 28);
        let PendingCmd::Add { attr, .. } = cmd else {
            panic!("expected an Add")
        };
        assert_eq!(attr.unwrap(), br#"{"abc":123,"def":"abc"}"#);
    }

    #[test]
    fn a_zero_vector_length_is_refused() {
        let msg = refusal("vadd index doc1 0");
        assert!(msg.contains("multiple of 4"), "{msg}");
    }

    #[test]
    fn a_non_numeric_vector_length_names_the_argument() {
        let msg = refusal("vadd index doc1 abc");
        assert!(msg.contains("vector length"), "{msg}");
    }

    #[test]
    fn a_truncated_vadd_line_is_refused() {
        assert!(refusal("vadd index doc1").contains("bad command line format"));
    }

    #[test]
    fn vsim_vector_length_errors_are_specific_too() {
        let msg = refusal("VSIM VECTOR docs 10 7 1024");
        assert!(msg.contains("vector bytes"), "{msg}");
        assert!(msg.contains("multiple of 4"), "{msg}");

        assert!(refusal("VSIM VECTOR docs 0 4096 1024").contains("result count"));
        assert!(refusal("VSIM VECTOR docs 10 4096 0").contains("dimension"));
    }

    #[test]
    fn attr_is_optional() {
        assert_eq!(attr_of("vadd docs v1 16").unwrap(), Vec::<u8>::new());
    }

    #[test]
    fn attr_is_read_off_the_command_line() {
        let json = r#"{"cat":"tech"}"#;
        assert_eq!(
            attr_of(&format!("vadd docs v1 16 ATTR {} {json}", json.len())).unwrap(),
            json.as_bytes()
        );
    }

    #[test]
    fn attr_with_spaces_is_reassembled() {
        let json = r#"{"cat": "tech", "ts": 1723248000}"#;
        assert_eq!(
            attr_of(&format!("vadd docs v1 16 ATTR {} {json}", json.len())).unwrap(),
            json.as_bytes()
        );
    }

    #[test]
    fn conventionally_spaced_json_is_accepted_up_to_the_byte_limit() {
        // json.dumps / jq style: one space after each comma. Fourteen fields is
        // 120 bytes with 13 spaces, well inside the token budget.
        let json = format!(
            "{{{}}}",
            (0..14)
                .map(|i| format!("\"k{i}\":{i}"))
                .collect::<Vec<_>>()
                .join(", ")
        );
        assert!(json.len() <= codec::ATTR_BYTES);
        assert_eq!(
            attr_of(&format!("vadd docs v1 16 ATTR {} {json}", json.len())).unwrap(),
            json.as_bytes()
        );
    }

    #[test]
    fn json_padded_with_whitespace_everywhere_hits_the_token_budget() {
        // memcached tokenizes on spaces and stops splitting at MAX_TOKENS, after
        // which the remaining length is not recoverable from the array we get.
        // Six fields spaced as `{ "k" : 0 , ... }` is only 67 bytes but already
        // 31 tokens, so it is refused with an actionable message instead of
        // being read past a bound we cannot verify.
        let body = (0..6)
            .map(|i| format!("\"k{i}\" : {i}"))
            .collect::<Vec<_>>()
            .join(" , ");
        let json = format!("{{ {body} }}");
        assert!(json.len() < codec::ATTR_BYTES, "{} bytes", json.len());

        let msg = attr_of(&format!("vadd docs v1 16 ATTR {} {json}", json.len()))
            .unwrap_err()
            .to_string();
        assert!(msg.contains("less whitespace"), "{msg}");
    }

    #[test]
    fn the_attr_keyword_is_case_insensitive() {
        assert!(attr_of("vadd docs v1 16 attr 2 {}").is_ok());
        assert!(attr_of("vadd docs v1 16 Attr 2 {}").is_ok());
    }

    #[test]
    fn a_missing_or_misspelled_keyword_is_reported() {
        let msg = attr_of("vadd docs v1 16 ATTRS 2 {}")
            .unwrap_err()
            .to_string();
        assert!(msg.contains("expected ATTR"), "{msg}");
    }

    #[test]
    fn a_declared_length_over_the_limit_is_rejected_before_reading() {
        // "미리 넘거나 하면 에러": the declared size alone is enough to refuse.
        let msg = attr_of("vadd docs v1 16 ATTR 129 {}")
            .unwrap_err()
            .to_string();
        assert!(msg.contains("over the 128-byte limit"), "{msg}");

        // Exactly at the limit is accepted. Built from real content, since
        // leading spaces are separators to the tokenizer, not part of the value.
        let json = format!(r#"{{"k":"{}"}}"#, "x".repeat(120));
        assert_eq!(json.len(), codec::ATTR_BYTES);
        assert!(attr_of(&format!("vadd docs v1 16 ATTR 128 {json}")).is_ok());
    }

    #[test]
    fn a_declared_length_that_disagrees_with_the_payload_is_rejected() {
        let msg = attr_of("vadd docs v1 16 ATTR 99 {}")
            .unwrap_err()
            .to_string();
        assert!(msg.contains("does not match"), "{msg}");
    }

    #[test]
    fn a_zero_length_attr_is_treated_as_absent() {
        assert_eq!(attr_of("vadd docs v1 16 ATTR 0").unwrap(), Vec::<u8>::new());
    }

    #[test]
    fn a_non_numeric_length_is_reported() {
        let msg = attr_of("vadd docs v1 16 ATTR abc {}")
            .unwrap_err()
            .to_string();
        assert!(msg.contains("ATTR length"), "{msg}");
    }
}
