//! ArcVector — vector similarity search as an arcus ASCII protocol extension.
//!
//! ```text
//! lib.rs           the C ABI — registration and memcached's four callbacks
//!   command/       the wire: a command line in, a typed request out   (pure)
//!   handler/       everything that runs a command
//!     arcus/         store vectors in the engine — the source of truth
//!     usearch/       search them — a cache of the arcus side
//!     registry/      the live pairs, and rebuilding one side from the other
//!   error          one error type, and who gets blamed for it
//! ```
//!
//! `command` names no engine and no index: it turns tokens into values and
//! stops. `handler` owns both backends, so the only way to reach the engine is
//! through the module that executes commands.
//!
//! The single consistency rule: **the usearch index is a cache rebuildable from
//! Map. If it is not in Map, it does not exist.**
//!
//! 구조·빌드·복구 로직은 `docs/내부구조.md`, 명령어 사용법은 `README.md`에 있다.

/// Bindings to arcus's `engine_interface_v1`, generated by bindgen in `build.rs`.
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    unnecessary_transmutes,
    clippy::all,
    clippy::pedantic
)]
pub mod engine_api {
    include!(concat!(env!("OUT_DIR"), "/engine_api.rs"));
}

pub mod command;
pub mod error;
pub mod handler;

/// Vocabulary the command line names, so parsing can spell it without reaching
/// into the modules that store or search by it.
///
/// `ATTR_BYTES` is here for the same reason: the parser has to refuse an
/// oversized `ATTR` before a handler ever sees it, and the size is a fact about
/// the stored element rather than about the wire.
pub use handler::arcus::element::{ATTR_BYTES, Quant};
pub use handler::usearch::Metric;

use std::os::raw::{c_char, c_int, c_void};
use std::ptr;

use command::pending;
use command::request::{self, MAX_BODY_BYTES};
use command::tokens::{Responder, ResponseHandler, Tokens};
use engine_api::{
    EXTENSION_ASCII_PROTOCOL_DESCRIPTOR, EXTENSION_ERROR_CODE,
    EXTENSION_ERROR_CODE_EXTENSION_FATAL, EXTENSION_ERROR_CODE_EXTENSION_SUCCESS, GET_SERVER_API,
    extension_type_t_EXTENSION_ASCII_PROTOCOL, token_t,
};

/// Decide how much body a command needs before it can run.
///
/// Only the byte count is examined. Everything else on the line is parsed too, but
/// a failure is *carried into* the pending state rather than refusing the command:
/// refusing would leave the body unread, and memcached would then parse those
/// bytes as the next command line.
///
/// Returning `true` without setting `ndata` is therefore reserved for a byte count
/// that cannot be read at all, since without one there is no way to know how much
/// to drain.
///
/// # Safety
///
/// `argv`, `ndata` and `ptr_out` must be the parameters memcached passed to the
/// `accept` callback.
unsafe extern "C" fn accept_vector_cmd(
    _cmd_cookie: *const c_void,
    cookie: *mut c_void,
    argc: c_int,
    argv: *mut token_t,
    ndata: *mut usize,
    ptr_out: *mut *mut c_char,
) -> bool {
    // SAFETY: guaranteed by the caller.
    let tokens = unsafe { Tokens::new(argv, argc) };

    let Some(at) = request::body_length_at(&tokens) else {
        // Either handled from the command line, or not ours at all.
        return tokens.command().is_some();
    };
    let Ok(body_len) = tokens.parse::<usize>(at, "length") else {
        return true;
    };
    if body_len > MAX_BODY_BYTES {
        return true;
    }

    // SAFETY: guaranteed by the caller.
    unsafe {
        pending::expect_body(
            cookie,
            request::parse_body(&tokens),
            body_len,
            ndata,
            ptr_out,
        );
    }
    true
}

/// # Safety
///
/// `argv` and `handler` must be the parameters memcached passed to `execute`.
unsafe extern "C" fn execute_vector_cmd(
    _cmd_cookie: *const c_void,
    cookie: *const c_void,
    argc: c_int,
    argv: *mut token_t,
    handler: ResponseHandler,
) -> bool {
    // SAFETY: guaranteed by the caller.
    let tokens = unsafe { Tokens::new(argv, argc) };
    // SAFETY: `cookie` belongs to the call in progress.
    let outcome = unsafe { handler::dispatch(cookie, &tokens) };
    Responder::new(handler, cookie).reply(outcome);
    true
}

/// Release a body whose command never completed.
unsafe extern "C" fn abort_vector_cmd(_cmd_cookie: *const c_void, cookie: *const c_void) {
    drop(pending::take_body(cookie));
}

unsafe extern "C" fn get_name_vector(_cmd_cookie: *const c_void) -> *const c_char {
    c"arcus-vector-db".as_ptr()
}

static mut VECTOR_DESCRIPTOR: EXTENSION_ASCII_PROTOCOL_DESCRIPTOR =
    EXTENSION_ASCII_PROTOCOL_DESCRIPTOR {
        get_name: Some(get_name_vector),
        get_auth_flag: None,
        accept: Some(accept_vector_cmd),
        execute: Some(execute_vector_cmd),
        abort: Some(abort_vector_cmd),
        cookie: ptr::null_mut(),
        next: ptr::null_mut(),
    };

/// Entry point memcached calls when loading the extension.
#[unsafe(no_mangle)]
pub extern "C" fn memcached_extensions_initialize(
    _config: *const c_char,
    get_server_api: GET_SERVER_API,
) -> EXTENSION_ERROR_CODE {
    let Some(get_api) = get_server_api else {
        return EXTENSION_ERROR_CODE_EXTENSION_FATAL;
    };
    handler::arcus::engine::set_server_api(get_api);

    // SAFETY: memcached hands us a live SERVER_HANDLE_V1 accessor, and the
    // descriptor is a process-lifetime static that the server only reads.
    unsafe {
        let server = get_api();
        if server.is_null() {
            return EXTENSION_ERROR_CODE_EXTENSION_FATAL;
        }
        let extension = (*server).extension;
        if extension.is_null() {
            return EXTENSION_ERROR_CODE_EXTENSION_FATAL;
        }
        let Some(register) = (*extension).register_extension else {
            return EXTENSION_ERROR_CODE_EXTENSION_FATAL;
        };
        if !register(
            extension_type_t_EXTENSION_ASCII_PROTOCOL,
            (&raw mut VECTOR_DESCRIPTOR).cast::<c_void>(),
        ) {
            return EXTENSION_ERROR_CODE_EXTENSION_FATAL;
        }
    }
    EXTENSION_ERROR_CODE_EXTENSION_SUCCESS
}
